[workspace]
resolver = "2" # What does this do?

[package]
name = "rui"
description = "Experimental Declarative UI library"
version = "0.2.1"
license = "MIT"
readme = "README.md"
authors = ["Taylor Holliday <taylor@audulus.com>"]
keywords = ["ui", "gui", "declarative"]
categories = ["gui"]
repository = "https://github.com/audulus/rui"
edition = "2018"
exclude = [ "screenshots/*" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.6"
tao = "0.6.3"
wgpu = "0.12.0"
futures = "0.3"
# vger = "0.1.7"
accesskit = "0.3.0"
lazy_static = "1.4.0"

vger = { path = "../vger-rs" } # TEMPORAY
nalgebra    = "0.30.0" # TODO: use euclid
fj-math = { path = "../fornjot/crates/fj-math" } # TODO: use euclid

